ORG 0000H

PORTA EQU 78H; LCD DATA PORT
PORTB EQU 79H; LCD CMD PORT
PORTC EQU 7AH; KEYPAD PORT
COMMAND EQU 7BH; 8255 COMMAND PORT

SERIALDATA EQU 80H; 8251 DATA PORT
SERIALCMD EQU 81H; 8251 COMMAND PORT

PROC PRINTCHAR
MOV AL, CL;
OUT C1PORTA, AL;
ENDP PRINTCHAR


; INITIALIZE SERIAL PORT
; 1111 1101 = 0xFD
MOV AL, 0FDH;
OUT SERIALCMD, AL;

; INITIALIZE 8255
; 1000 1000 = 0x88
MOV AL, 88H;
OUT COMMAND, AL;

; CLEAR SCREEN
MOV AL, 0;
OUT PORTB, AL;



XOR AX, AX;
XOR BX, BX;
MOV BX, FEH;
READLOOP: 
OUT PORTC, BL;
IN AL, PORTC;
TEST AL, FFH;
JZ READLOOP;
;; READ CURRENT BL AND AL TO SELECT CHARACTER AND STORE IN CL
CALL PRINTCHAR;
JMP READLOOP;

